CREATE TABLE cajas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL
);

CREATE TABLE objetos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  caja_id INTEGER NOT NULL,
  numero INTEGER NOT NULL,
  FOREIGN KEY(caja_id) REFERENCES cajas(id)
);
